gemini.api.key=${GEMINI_API_KEY:}
gemini.model=gemini-2.5-flash
spring.application.name=backend
server.port=8016
chatbot.service.url=${CHATBOT_SERVICE_URL:http://localhost:5001}

# H2 Database Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:aarogyamitra;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Razorpay Properties
razorpay.key.id=${RAZORPAY_KEY_ID:}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:}

